name = "UI Library"
license = "MIT"
licenselink = "https://github.com/pkgstore/hugo-ui-library/blob/main/LICENSE"
description = "WebSite User Interface"
homepage = "https://v77.dev"
tags = ["website", "responsive", "multilingual", "mobile"]
features = ["posts", "shortcodes", "comments"]
min_version = "0.82.0"

[author]
  name = "v77 Development"
  homepage = "https://v77.dev"
